version: "3"

services:
  tinderbotft:
    image: tinderbotft
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm start
    restart: always
